name: 'AI Function & Schema Validator'
description: 'Валидация функций и генерация отчета'

inputs:
  func_path:
    description: 'Путь к .py файлу функции'
    required: true
  schema_path:
    description: 'Путь к .json файлу схемы'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Run Pytest Validation
      shell: bash
      run: |
        # Заходим в папку экшена для синхронизации зависимостей
        cd ${{ github.action_path }}
        uv sync
        
        # Прокидываем пути. ВАЖНО: PYTHONPATH должен видеть src внутри экшена
        export PYTHONPATH="$PYTHONPATH:${{ github.action_path }}"
        export INPUT_FUNC_PATH="${{ github.workspace }}/${{ inputs.func_path }}"
        export INPUT_SCHEMA_PATH="${{ github.workspace }}/${{ inputs.schema_path }}"
        

        ALLURE_RESULTS_DIR="${{ github.workspace }}/allure-results"

        uv run pytest "${{ github.action_path }}/runner.py" \
          --alluredir="$ALLURE_RESULTS_DIR" \
          --clean-alluredir \
          -v

      continue-on-error: true

    - name: Generate Allure Report
      shell: bash
      run: |
        # Используем тот же абсолютный путь
        ALLURE_RESULTS_DIR="${{ github.workspace }}/allure-results"
        
        echo "🔍 Checking results directory: $ALLURE_RESULTS_DIR"
        if [ -d "$ALLURE_RESULTS_DIR" ]; then
          ls -la "$ALLURE_RESULTS_DIR"
        else
          echo "❌ Directory not found!"
          exit 1
        fi

        # Установка зависимостей Node (если нужно)
        if [ ! -d "${{ github.action_path }}/node_modules" ]; then
          cd ${{ github.action_path }} && npm install
        fi

        echo "📊 Generating Allure Report..."
        # Передаем абсолютный путь в команду генерации
        npx allure awesome "$ALLURE_RESULTS_DIR" \
          --config ${{ github.action_path }}/allurerc.yaml