name: 'AI Function & Schema Validator'
description: 'Валидация функций и генерация отчета'

inputs:
  func_path:
    description: 'Путь к .py файлу функции'
    required: true
  schema_path:
    description: 'Путь к .json файлу схемы'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Run Pytest Validation
      shell: bash
      run: |
        # Заходим в папку экшена для синхронизации зависимостей
        cd ${{ github.action_path }}
        uv sync
        
        # Прокидываем пути. ВАЖНО: PYTHONPATH должен видеть src внутри экшена
        export PYTHONPATH="$PYTHONPATH:${{ github.action_path }}"
        export INPUT_FUNC_PATH="${{ github.workspace }}/${{ inputs.func_path }}"
        export INPUT_SCHEMA_PATH="${{ github.workspace }}/${{ inputs.schema_path }}"
        

        uv run pytest "${{ github.action_path }}/runner.py" 
      continue-on-error: true

    - name: Generate Allure Report
      shell: bash
      run: |
        # Устанавливаем Node зависимости для Allure Awesome, если их нет
        if [ ! -d "${{ github.action_path }}/node_modules" ]; then
          cd ${{ github.action_path }} && npm install
        fi

        # Генерируем отчет из результатов работы pytest
        npx allure awesome ${{ github.workspace }}/allure-results \
          --config ${{ github.action_path }}/allurerc.yaml 
